name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out the repo
        run: docker build
      - name: Push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./src/Dockerfile
          image : nessgis/users-api
          tags: latest
          registry : docker.io