name: Publish Docker image
on:
  push:
    branches: [ master ]
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: src
          file: ./src/Dockerfile
          push: true
          tags: nessgis/users-api:latest