

name: CI


on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker-compose up -d --build
      - name: run
        run: docker run --network container:users-api
      - name: list containers
        run: docker ps -a
